# Generated by Django 4.1.7 on 2023-04-27 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('signage', '0001_initial'), ('signage', '0002_alter_display_code_scheduleentry'), ('signage', '0003_remove_scheduleentry_display_scheduleentry_displays'), ('signage', '0004_scheduleentry_end_date_scheduleentry_priority_and_more'), ('signage', '0005_schedulesequenceitem'), ('signage', '0006_remove_scheduleentry_page')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=512)),
                ('mime_type', models.CharField(default='text/html', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('displays', models.ManyToManyField(blank=True, to='signage.display')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSequenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signage.page')),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='signage.scheduleentry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
