# Generated by Django 4.1.7 on 2023-04-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='display',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='scheduleentry',
            options={'ordering': ['start_date', 'start_time', '-priority']},
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schedulesequenceitem',
            name='duration',
            field=models.FloatField(default=1, help_text='Duration in minutes'),
        ),
    ]
