# Generated by Django 4.1.7 on 2023-04-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_alter_display_options_alter_scheduleentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cover',
            field=models.BooleanField(default=False, help_text='Whether images should be cropped and upscaled to cover the entire page, instead of being fully contained inside the page'),
        ),
    ]
