# Generated by Django 4.1.7 on 2023-04-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_alter_display_code_scheduleentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='display',
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='displays',
            field=models.ManyToManyField(to='signage.display'),
        ),
    ]
