# Generated by Django 4.1.7 on 2023-04-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0003_remove_scheduleentry_display_scheduleentry_displays'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='displays',
            field=models.ManyToManyField(blank=True, to='signage.display'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
