# Generated by Django 4.1.7 on 2023-04-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0004_schedulesequenceitem_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesequenceitem',
            name='params',
            field=models.JSONField(default=dict),
        ),
    ]
