# Generated by Django 4.1.7 on 2023-04-27 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0004_scheduleentry_end_date_scheduleentry_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSequenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signage.page')),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='signage.scheduleentry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
