# Generated by Django 4.1.7 on 2023-04-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0005_schedulesequenceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='page',
        ),
    ]
